#!/system/bin/sh
# Device info properties and various device environment variables

# Device Information
# If the device's values from default.prop aren't correct or don't make sense,
# it might make more sense to just fill this out by hand.
export DEVICE_MANUFACTURER=`getprop ro.product.manufacturer`
export DEVICE_MODEL=`getprop ro.product.model`
export DEVICE_NAME="$DEVICE_MANUFACTURER $DEVICE_MODEL"
export DEVICE_CODENAME=`echo $DEVICE_MODEL | tr "[:upper:]" "[:lower:]"`

# Device screen configuration
# Screen rotation (in 90°CW increments): 1 for 90°CW, 2 for 180°CW, or 3 for 270°CW
export SDL_SCREEN_ROTATION=0
# Skip the SDL encoder ID check (Unisoc devices report invalid encoder IDs)
export SDL_SKIP_ENCODER_ID_CHECK=true
# Tell SDL to blacklist unwanted joysticks
export SDL_JOYSTICK_DEVICE_BLACKLIST=unwanted:inputdevice:names
